language: node_js
sudo: false
node_js:
  - '7'
  - '6'
  - '4'
cache:
    directories:
      - $HOME/.npm
before_install:
  - npm config set registry https://:2022-02-24T17%3A58%3A20.816000Z@time-machines-npm.sealsecurity.io/
