name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 17.x]
        platform:
        - os: ubuntu-22.04
          shell: bash
        - os: macos-14
          shell: bash
        - os: windows-2022
          shell: bash
        - os: windows-2022
          shell: powershell
        exclude:
        - node-version: 12.x
          platform:
            os: macos-14
        - node-version: 14.x
          platform:
            os: macos-14
      fail-fast: false

    runs-on: ${{ matrix.platform.os }}
    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Use Nodejs ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install

    - name: Run Tests
      run: npm test -- -c -t0
